version: "3.7"

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      - LOGSPOUT=ignore
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - XPACK_MONITORING_ENABLED=false
      - XPACK_SECURITY_ENABLED=false
      - server.port=5601
      - server.host=0.0.0.0
      - elasticsearch.hosts=http://localhost:9200
    links:
      - elasticsearch
    ports:
      - 5601:5601

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - LOGSPOUT=ignore
      - node.name=dev-log-kibana
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
      - xpack.graph.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - network.host=0.0.0.0
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  logspout:
    image: gliderlabs/logspout:v3.2.8
    command: syslog://logstash:5000
    environment:
      - RETRY_COUNT=100
    links:
      - logstash
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  logstash:
    image: docker.elastic.co/logstash/logstash:7.6.2
    environment:
      - LOGSPOUT=ignore
      - XPACK_MONITORING_ENABLED=false
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf